### ISSUE TITLE
Syllabus no longer renders when using blogdown::serve_site() 

### ISSUE THREAD

**Issue by jvcasillas** [espm-157/website#2]
Hello, 

I came across your site on the internet and made a modified version for one of my course websites. I find it to a fantastic template to work with and I wanted to say thanks for this. I've noticed that the syllabus portion of the site no longer renders as it used to. I assume this is due to some blogdown update, but I'm not sure yet. In any case, I wanted to let you know (I'm assuming you haven't come across this yet). If I come across a workaround I will let you know. If you already happen to have a solution for this could you please let me know? Thank you once again for making this wonderful resource.

**Comment by cboettig** [comment]
thanks for the ping, should be fixed.
